### PR TITLE
Add: Two new categories and updated GoPlausible content

### PR DESCRIPTION
**Pull request by emg110**
<div align="center">
<a href="https://github.com/awesome-algorand/awesome-algorand"></a>
</div>
<br/>

# Pull Request Summary
_Briefly describe the resource you're suggesting:_

Two new categories "SSI , DIDs and VCs" and "AI, ML and Datascience" have been added. GoPlausible content have been updated

# Checklist
_Review and comply with each requirement:_

## For AwesomeAlgo Resources:
- [x] Follows [contribution guidelines](../contributing.md)
- [x] PR title format: `{Resource Name} - brief description`
- [x] Aware that PR title will be used in automated tweet

- [ ] Updated [AlgoHelp](https://github.com/awesome-algorand/awesome-algorand/blob/main/markdown/algohelp.md) file

> Ensure your PR passes linters in [GitHub Actions pipeline](https://github.com/awesome-algorand/awesome-algorand/actions/workflows/ci.yaml) for prompt review.

### Optional: AwesomeAlgo Podcast
Interested in discussing your contribution? [Sign up here](https://2c5n1ed3kz6.typeform.com/to/pAP5oPFx)

### CODE REVIEW

**Comment by aorumbayev** [comment]
Hey @emg110 thank you as always for contribution and happy upcoming New Year! :-) 

Just a few minor linting bugs to address after that we are good to go:

```
 README.md:27:3
  ✖   27:1   ToC item "Awesome Algorand " does not match corresponding heading "Official Resources"  remark-lint:awesome-toc
  ✖   27:3   Don’t pad link with inner spaces                                                        remark-lint:no-inline-padding
  ✖  387:41  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
  ✖  421:64  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
```

The TOC in your diff looks very different from the one on main readme, I'd suggest rebasing against latest on main or copying existing TOC and adding extra sections of yours again.

**Review by aorumbayev — CHANGES_REQUESTED** [review]
Hey @emg110 thank you as always for contribution and happy upcoming New Year! :-) 

Just a few minor linting bugs to address after that we are good to go:

```
 README.md:27:3
  ✖   27:1   ToC item "Awesome Algorand " does not match corresponding heading "Official Resources"  remark-lint:awesome-toc
  ✖   27:3   Don’t pad link with inner spaces                                                        remark-lint:no-inline-padding
  ✖  387:41  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
  ✖  421:64  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
```

The TOC in your diff looks very different from the one on main readme, I'd suggest rebasing against latest on main or copying existing TOC and adding extra sections of yours again.

**Comment by emg110** [comment]
> Hey @emg110 thank you as always for contribution and happy upcoming New Year! :-)
> 
> Just a few minor linting bugs to address after that we are good to go:
> 
> ```
>  README.md:27:3
>   ✖   27:1   ToC item "Awesome Algorand " does not match the corresponding heading "Official Resources"  remark-lint:awesome-toc
>   ✖   27:3   Don’t pad link with inner spaces                                                        remark-lint:no-inline-padding
>   ✖  387:41  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
>   ✖  421:64  List item description must end with proper punctuation                                  remark-lint:awesome-list-item
> ```
> 
> The TOC in your diff looks very different from the one on the main readme, I'd suggest rebasing against the latest on the main or copying the existing TOC and adding extra sections of yours again.

Thank you so much, Happy new year and best wishes in advance. The reason is Remark as VS Code and Remark in CLI for example act a little different, I am addressing those differences and fixing them manually and some got resolved and the rest will be, when the checks all pass then it will be reviewed for merge. Many thanks again for the Awesome resource here (and a million other things you do).

**Comment by emg110** [comment]
Checked and Lint succeeded
Screenshot 2024-12-29 at 14 33 03

**Pull request merged**
